#
#   SPDX-FileCopyrightText: Copyright 2024-2025 Julian Amann <dev@vertexwahn.de>
#   SPDX-License-Identifier: Apache-2.0
#

# Apple Clang 15 on macOS 14 (Sonoma)
# Make sure we can build with Apple Clang13 in all different compilation modes
steps:
  - script: |
      df -h
    displayName: "Show disk space"

  - checkout: self
    clean: true
    fetchDepth: 1
    lfs: false
    submodules: false

  - script: |
      df -h
    displayName: "Show disk space"

  - script: |
      sw_vers
      uname
    displayName: "Show OS version"

  - script: |
      sysctl -a | grep machdep.cpu
    displayName: "Show CPU info"

  - script: |
      cd devertexwahn
      bazel version
    displayName: "Show Bazel version"

  - script: |
      clang --version
    displayName: "Show Clang version"




  # fastbuild
  - script: |
      cd devertexwahn
      bazel build --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel build macos-fastbuild"

  - script: |
      cd devertexwahn
      bazel test --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel test macos-fastbuild"

  # dbg
  - script: |
      cd devertexwahn
      bazel build --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} --compilation_mode=dbg -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel build macos-dbg"

  - script: |
      cd devertexwahn
      bazel test --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} --compilation_mode=dbg -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel test macos-dbg"

  # opt
  - script: |
      cd devertexwahn
      bazel build --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} --compilation_mode=opt -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel build macos-opt"

  - script: |
      cd devertexwahn
      bazel test --config=macos --config=buildbuddy_remote_cache --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY} --compilation_mode=opt -- //...   
    env:
      BUILDBUDDY_API_KEY: $(BUILDBUDDY_API_KEY)
    displayName: "Bazel test macos-opt"

  - script: |
      df -h
    displayName: "Show disk space"
