#
#   SPDX-FileCopyrightText: Copyright 2026 Julian Amann <dev@vertexwahn.de>
#   SPDX-License-Identifier: Apache-2.0
#

# Bazel build and test

name: Bazel

on:
  push:
    paths:
      - .github/workflows/**
      - devertexwahn/**
      - third_party/**
  pull_request:
    paths:
      - .github/workflows/**
      - devertexwahn/**
      - third_party/**

jobs:
  macos_26_apple_clang17:
    uses: ./.github/workflows/macOS-26-apple-clang17.yaml
