#
#   SPDX-FileCopyrightText: Copyright 2026 Julian Amann <dev@vertexwahn.de>
#   SPDX-License-Identifier: Apache-2.0
#

# Apple Clang 17 on macOS 26 (Tahoe)
# Make sure we can build with Apple Clang16 in all different compilation modes
name: Apple Clang16 on macOS 26 (Tahoe)

on:
  workflow_call:

permissions:
  contents: read

#on:
#  schedule:
#    - cron: "0 0 * * *"
#  #push: {}
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  build_and_test_macos15:
    name: "Apple Clang17 on macOS 26 (Tahoe)"
    runs-on: macos-26
    #runs-on: macos-15  # GitHub hosted runner
    steps:
      - name: "Show disk space"
        run: |
          df -h

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Show disk space"
        run: |
          df -h

      - name: "Show OS version"
        run: |
          sw_vers
          uname

      - name: "Show CPU info"
        run: |
          sysctl -a | grep machdep.cpu

      - name: "Show Bazel version"
        run: |
          cd devertexwahn
          bazel version

      - name: "Show Clang version"
        run: |
          clang --version

      - name: "Regenerate lock files for Python"
        run: |
          cd devertexwahn
          bazel run --config=macos -- //bazel/module/python:requirements.update

      # Was here to recover for some strange build error
      # Not sure what it caused - maybe switch form Bazel 8 to 9?
      #- name: "Bazel clean"
      #  run: |
      #    cd devertexwahn
      #    bazel clean --expunge

      # fastbuild
      - name: "Bazel build macos-fastbuild"
        run: |
          cd devertexwahn
          bazel build --config=macos -- //...

      - name: "Bazel test macos-fastbuild"
        run: |
          cd devertexwahn
          bazel build --config=macos -- //...

      # dbg
      - name: "Bazel build macos-dbg"
        run: |
          cd devertexwahn
          bazel build --config=macos --compilation_mode=dbg -- //...

      - name: "Bazel test macos-dbg"
        run: |
          cd devertexwahn
          bazel build --config=macos --compilation_mode=dbg -- //...

      # opt
      - name: "Bazel build macos-opt"
        run: |
          cd devertexwahn
          bazel build --config=macos --compilation_mode=opt -- //...

      - name: "Bazel test macos-opt"
        run: |
          cd devertexwahn
          bazel build --config=macos --compilation_mode=opt -- //...
